# Location and name of the output image relative to the root of the repository
outputPath: ".github/og-image.png" 

# Name of the template file 
templateFileName: "template.html"

# Location and name of the background image
backgroundImage: "assets/images/background-stars.png"

# The following are optional, and will be used to generate the image.
repo:
  owner: "octocat" # The owner of the repository (usually your Github username)
  name: "Spoon-Knife" # The name of the repository.

# Which elements should be included in the image?
elements:
  nameWithOwner: true
  description: true
  ownerLogo: true
  stats: true
  linguist: true